const fs = require('fs');
const path = require('path');

const catalog = [
  // ==========================================
  // 1. DOLPHIN & ANALGESICS & NSAIDs & MUSCLE RELAXANTS
  // ==========================================
  { id: 'drug-dolph-1', name: 'Dolphin 12.5mg Suppositories', nameAr: 'دولفين 12.5 مجم أقماع (لبوس للأطفال الرضع)', activeIngredient: 'Diclofenac Sodium (12.5mg)', company: 'Delta Pharma', price: 27, dosageForm: 'Suppositories (أقماع/لبوس)', category: 'NSAID / Analgesic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-dolph-2', name: 'Dolphin 25mg Suppositories', nameAr: 'دولفين 25 مجم أقماع (لبوس للأطفال)', activeIngredient: 'Diclofenac Sodium (25mg)', company: 'Delta Pharma', price: 31.5, dosageForm: 'Suppositories (أقماع/لبوس)', category: 'NSAID / Analgesic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-dolph-3', name: 'Dolphin 50mg Suppositories', nameAr: 'دولفين 50 مجم أقماع (لبوس للأطفال والكبار)', activeIngredient: 'Diclofenac Sodium (50mg)', company: 'Delta Pharma', price: 38, dosageForm: 'Suppositories (أقماع/لبوس)', category: 'NSAID / Analgesic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-dolph-4', name: 'Dolphin 75mg Suppositories', nameAr: 'دولفين 75 مجم أقماع (لبوس للكبار)', activeIngredient: 'Diclofenac Sodium (75mg)', company: 'Delta Pharma', price: 45, dosageForm: 'Suppositories (أقماع/لبوس)', category: 'NSAID / Analgesic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-dolph-5', name: 'Dolphin K 25mg Suppositories', nameAr: 'دولفين كي 25 مجم أقماع (لبوس أطفال)', activeIngredient: 'Diclofenac Potassium (25mg)', company: 'Delta Pharma', price: 33, dosageForm: 'Suppositories (أقماع/لبوس)', category: 'NSAID / Analgesic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-dolph-6', name: 'Dolphin 75mg/3ml 6 Ampoules', nameAr: 'دولفين 75 مجم / 3 مل 6 أمبولات (حقن عضل)', activeIngredient: 'Diclofenac Sodium (75mg)', company: 'Delta Pharma', price: 54, dosageForm: 'Injection Ampoule', category: 'NSAID / Analgesic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-dolph-7', name: 'Dolphin Topical Gel 50g', nameAr: 'دولفين جل 50 جرام (مسكن ومضاد للروماتيزم)', activeIngredient: 'Diclofenac Sodium 1%', company: 'Delta Pharma', price: 28, dosageForm: 'Topical Gel', category: 'Topical Analgesic', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-cata-1', name: 'Cataflam 25mg 20 Tablets', nameAr: 'كتافلام 25 مجم 20 قرص', activeIngredient: 'Diclofenac Potassium (25mg)', company: 'Novartis', price: 46, dosageForm: 'Tablet', category: 'Analgesic / NSAID', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-cata-2', name: 'Cataflam 50mg 20 Tablets', nameAr: 'كتافلام 50 مجم 20 قرص', activeIngredient: 'Diclofenac Potassium (50mg)', company: 'Novartis', price: 63, dosageForm: 'Tablet', category: 'Analgesic / NSAID', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-cata-3', name: 'Cataflam Dispersible 50mg 10 Tablets', nameAr: 'كتافلام 50 مجم أقراص فوارة سريعة الذوبان', activeIngredient: 'Diclofenac Free Acid (50mg)', company: 'Novartis', price: 38, dosageForm: 'Dispersible Tablet', category: 'Analgesic / NSAID', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-cata-4', name: 'Cataflam 75mg/3ml 6 Ampoules', nameAr: 'كتافلام 75 مجم أمبولات (حقن عضل)', activeIngredient: 'Diclofenac Potassium (75mg)', company: 'Novartis', price: 72, dosageForm: 'Injection Ampoule', category: 'Analgesic / NSAID', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-cata-5', name: 'Catafly Oral Suspension 140ml', nameAr: 'كتافلاي معلق 140 مل للأطفال', activeIngredient: 'Diclofenac Resinate', company: 'Novartis', price: 35, dosageForm: 'Oral Suspension', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-volt-1', name: 'Voltaren 50mg 20 Tablets', nameAr: 'فولتارين 50 مجم أقراص مغلفة', activeIngredient: 'Diclofenac Sodium (50mg)', company: 'Novartis', price: 58, dosageForm: 'Tablet', category: 'Analgesic / NSAID', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-volt-2', name: 'Voltaren 100mg SR 10 Capsules', nameAr: 'فولتارين 100 مجم كبسولات ممتدة المفعول', activeIngredient: 'Diclofenac Sodium (100mg)', company: 'Novartis', price: 65, dosageForm: 'SR Capsule', category: 'Analgesic / NSAID', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-volt-3', name: 'Voltaren 75mg/3ml 6 Ampoules', nameAr: 'فولتارين 75 مجم أمبولات حقن عضل', activeIngredient: 'Diclofenac Sodium (75mg)', company: 'Novartis', price: 78, dosageForm: 'Injection Ampoule', category: 'Analgesic / NSAID', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-volt-4', name: 'Voltaren Emulgel 50g', nameAr: 'فولتارين إيملجل 50 جرام مسكن روماتيزمي', activeIngredient: 'Diclofenac Diethylamine 1.16%', company: 'Novartis', price: 42, dosageForm: 'Topical Gel', category: 'Topical Analgesic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-volt-5', name: 'Voltaren 12.5mg Suppositories', nameAr: 'فولتارين 12.5 مجم أقماع (لبوس رضع)', activeIngredient: 'Diclofenac Sodium (12.5mg)', company: 'Novartis', price: 24, dosageForm: 'Suppositories (أقماع/لبوس)', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-volt-6', name: 'Voltaren 25mg Suppositories', nameAr: 'فولتارين 25 مجم أقماع (لبوس أطفال)', activeIngredient: 'Diclofenac Sodium (25mg)', company: 'Novartis', price: 29, dosageForm: 'Suppositories (أقماع/لبوس)', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-volt-7', name: 'Voltaren 100mg Suppositories', nameAr: 'فولتارين 100 مجم أقماع (لبوس للكبار)', activeIngredient: 'Diclofenac Sodium (100mg)', company: 'Novartis', price: 48, dosageForm: 'Suppositories (أقماع/لبوس)', category: 'Analgesic / NSAID', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-bruf-1', name: 'Brufen 200mg 30 Tablets', nameAr: 'بروفين 200 مجم 30 قرص', activeIngredient: 'Ibuprofen (200mg)', company: 'Abbott', price: 31, dosageForm: 'Tablet', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-bruf-2', name: 'Brufen 400mg 30 Tablets', nameAr: 'بروفين 400 مجم 30 قرص', activeIngredient: 'Ibuprofen (400mg)', company: 'Abbott', price: 54, dosageForm: 'Tablet', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-bruf-3', name: 'Brufen 600mg 30 Tablets', nameAr: 'بروفين 600 مجم 30 قرص', activeIngredient: 'Ibuprofen (600mg)', company: 'Abbott', price: 69, dosageForm: 'Tablet', category: 'Analgesic / Anti-inflammatory', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-bruf-4', name: 'Brufen 800mg Retard 20 Tablets', nameAr: 'بروفين 800 مجم أقراص ممتدة المفعول', activeIngredient: 'Ibuprofen (800mg)', company: 'Abbott', price: 58, dosageForm: 'SR Tablet', category: 'Analgesic / Anti-inflammatory', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-bruf-5', name: 'Brufen Syrup 110ml', nameAr: 'بروفين شراب 110 مل خافض حرارة للأطفال', activeIngredient: 'Ibuprofen (100mg/5ml)', company: 'Abbott', price: 23.5, dosageForm: 'Syrup', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-bruf-6', name: 'Brufen Flu 20 Tablets', nameAr: 'بروفين فلو 20 قرص لعلاج نزلات البرد والاحتقان', activeIngredient: 'Ibuprofen (400mg) + Pseudoephedrine (60mg)', company: 'Abbott', price: 44, dosageForm: 'Tablet', category: 'Cold & Flu', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-pana-1', name: 'Panadol Extra 24 Tablets', nameAr: 'بنادول إكسترا 24 قرص مسكن للألم', activeIngredient: 'Paracetamol 500mg + Caffeine 65mg', company: 'GlaxoSmithKline (GSK)', price: 45, dosageForm: 'Tablet', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-pana-2', name: 'Panadol Advance 24 Tablets', nameAr: 'بنادول أدفانس 24 قرص سريع المفعول', activeIngredient: 'Paracetamol 500mg (Optizorb)', company: 'GlaxoSmithKline (GSK)', price: 37, dosageForm: 'Tablet', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-pana-3', name: 'Panadol Joint 24 Tablets', nameAr: 'بنادول جوينت 24 قرص لمشاكل وآلام المفاصل', activeIngredient: 'Paracetamol 665mg SR', company: 'GlaxoSmithKline (GSK)', price: 52, dosageForm: 'SR Tablet', category: 'Analgesic / Joint Care', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-pana-4', name: 'Panadol Cold & Flu Day 24 Tablets', nameAr: 'بنادول كولد أند فلو داي (نهار)', activeIngredient: 'Paracetamol + Phenylephrine + Vitamin C', company: 'GlaxoSmithKline (GSK)', price: 42, dosageForm: 'Tablet', category: 'Cold & Flu', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-pana-5', name: 'Panadol Night 24 Tablets', nameAr: 'بنادول نايت 24 قرص مسكن ومساعد على النوم', activeIngredient: 'Paracetamol 500mg + Diphenhydramine 25mg', company: 'GlaxoSmithKline (GSK)', price: 46, dosageForm: 'Tablet', category: 'Cold & Flu / Sleep Aid', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-pana-6', name: 'Panadol Baby & Infant Suspension 100ml', nameAr: 'بنادول بيبي للأطفال والرضع معلق 100 مل', activeIngredient: 'Paracetamol (120mg/5ml)', company: 'GlaxoSmithKline (GSK)', price: 29, dosageForm: 'Oral Suspension', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-ceta-1', name: 'Cetal 500mg 20 Tablets', nameAr: 'سيتال 500 مجم 20 قرص', activeIngredient: 'Paracetamol 500mg', company: 'EIPICO', price: 16.5, dosageForm: 'Tablet', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-ceta-2', name: 'Cetal Syrup 120ml', nameAr: 'سيتال شراب 120 مل خافض للحرارة', activeIngredient: 'Paracetamol (120mg/5ml)', company: 'EIPICO', price: 14.5, dosageForm: 'Syrup', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-ceta-3', name: 'Cetal Oral Drops 15ml', nameAr: 'سيتال نقط للفم للأطفال الرضع 15 مل', activeIngredient: 'Paracetamol (100mg/ml)', company: 'EIPICO', price: 10.5, dosageForm: 'Oral Drops', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-ceta-4', name: 'Cetal 120mg Suppositories', nameAr: 'سيتال 120 مجم أقماع (لبوس للأطفال الرضع)', activeIngredient: 'Paracetamol 120mg', company: 'EIPICO', price: 12, dosageForm: 'Suppositories (أقماع/لبوس)', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-ceta-5', name: 'Cetal 300mg Suppositories', nameAr: 'سيتال 300 مجم أقماع (لبوس للأطفال)', activeIngredient: 'Paracetamol 300mg', company: 'EIPICO', price: 15, dosageForm: 'Suppositories (أقماع/لبوس)', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-abim-1', name: 'Abimol 500mg 20 Tablets', nameAr: 'أبيمول 500 مجم 20 قرص', activeIngredient: 'Paracetamol 500mg', company: 'GlaxoSmithKline (GSK)', price: 15, dosageForm: 'Tablet', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-abim-2', name: 'Abimol Syrup 120ml', nameAr: 'أبيمول شراب 120 مل للأطفال', activeIngredient: 'Paracetamol (150mg/5ml)', company: 'GlaxoSmithKline (GSK)', price: 13, dosageForm: 'Syrup', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-abim-3', name: 'Abimol 300mg Suppositories', nameAr: 'أبيمول 300 مجم أقماع (لبوس أطفال)', activeIngredient: 'Paracetamol 300mg', company: 'GlaxoSmithKline (GSK)', price: 14, dosageForm: 'Suppositories (أقماع/لبوس)', category: 'Analgesic / Antipyretic', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-alph-1', name: 'Alphintern 30 Tablets', nameAr: 'الفينترن 30 قرص مضاد للتورم والالتهابات', activeIngredient: 'Trypsin + Chymotrypsin', company: 'Amoun', price: 54, dosageForm: 'Tablet', category: 'Anti-edematous / Anti-inflammatory', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-ambi-1', name: 'Ambizim 30 Capsules', nameAr: 'أمبيزيم 30 كبسول للارتشاح والتورم', activeIngredient: 'Trypsin + Chymotrypsin', company: 'Sanofi', price: 48, dosageForm: 'Capsule', category: 'Anti-inflammatory', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-dimr-1', name: 'Dimra 20 Tablets', nameAr: 'ديمرا 20 قرص باسط للعضلات ومسكن للألم', activeIngredient: 'Methocarbamol 500mg + Diclofenac Potassium 50mg', company: 'Marcher', price: 42, dosageForm: 'Tablet', category: 'Muscle Relaxant / Analgesic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-myof-1', name: 'Myofen 30 Capsules', nameAr: 'مايوفين 30 كبسول باسط للعضلات ومسكن', activeIngredient: 'Chlorzoxazone 250mg + Ibuprofen 200mg', company: 'EVA Pharma', price: 36, dosageForm: 'Capsule', category: 'Muscle Relaxant', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-mark-1', name: 'Markfast 20 Capsules', nameAr: 'مارك فاست 20 كبسول لعلاج تقلص العضلات', activeIngredient: 'Chlorzoxazone 250mg + Paracetamol 300mg', company: 'Marcyrl', price: 31.5, dosageForm: 'Capsule', category: 'Muscle Relaxant', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-keto-1', name: 'Ketofan 50mg 20 Capsules', nameAr: 'كيتوفان 50 مجم 20 كبسولة مسكن ومضاد للروماتيزم', activeIngredient: 'Ketoprofen 50mg', company: 'Amoun', price: 28, dosageForm: 'Capsule', category: 'Analgesic / NSAID', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-keto-2', name: 'Ketofan 100mg SR 20 Capsules', nameAr: 'كيتوفان 100 مجم كبسولات ممتدة المفعول', activeIngredient: 'Ketoprofen 100mg', company: 'Amoun', price: 38, dosageForm: 'SR Capsule', category: 'Analgesic / NSAID', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-keto-3', name: 'Ketofan 100mg/2ml 6 Ampoules', nameAr: 'كيتوفان 100 مجم 6 أمبولات حقن عضل', activeIngredient: 'Ketoprofen 100mg', company: 'Amoun', price: 42, dosageForm: 'Injection Ampoule', category: 'Analgesic / NSAID', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-keto-4', name: 'Ketofan 100mg Suppositories', nameAr: 'كيتوفان 100 مجم أقماع (لبوس للكبار)', activeIngredient: 'Ketoprofen 100mg', company: 'Amoun', price: 22, dosageForm: 'Suppositories (أقماع/لبوس)', category: 'Analgesic / NSAID', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-feld-1', name: 'Feldene 20mg 10 Capsules', nameAr: 'فيلدين 20 مجم 10 كبسولات', activeIngredient: 'Piroxicam 20mg', company: 'Pfizer', price: 32, dosageForm: 'Capsule', category: 'NSAID', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-feld-2', name: 'Feldene Flash 20mg 10 Tablets', nameAr: 'فيلدين فلاش 20 مجم أقراص سريع الذوبان', activeIngredient: 'Piroxicam 20mg', company: 'Pfizer', price: 39, dosageForm: 'Dispersible Tablet', category: 'NSAID', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  // ==========================================
  // 2. ANTIBIOTICS & ANTIMICROBIALS & ANTISEPTICS
  // ==========================================
  { id: 'drug-augm-1', name: 'Augmentin 1g 14 Tablets', nameAr: 'أوجمنتين 1 جرام 14 قرص مضاد حيوي', activeIngredient: 'Amoxicillin 875mg + Clavulanic Acid 125mg', company: 'GlaxoSmithKline (GSK)', price: 115, dosageForm: 'Tablet', category: 'Broad Spectrum Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-augm-2', name: 'Augmentin 625mg 10 Tablets', nameAr: 'أوجمنتين 625 مجم 10 أقراص', activeIngredient: 'Amoxicillin 500mg + Clavulanic Acid 125mg', company: 'GlaxoSmithKline (GSK)', price: 78, dosageForm: 'Tablet', category: 'Broad Spectrum Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-augm-3', name: 'Augmentin 375mg 10 Tablets', nameAr: 'أوجمنتين 375 مجم 10 أقراص', activeIngredient: 'Amoxicillin 250mg + Clavulanic Acid 125mg', company: 'GlaxoSmithKline (GSK)', price: 52, dosageForm: 'Tablet', category: 'Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-augm-4', name: 'Augmentin 457mg/5ml Suspension 70ml', nameAr: 'أوجمنتين 457 مجم معلق 70 مل للأطفال', activeIngredient: 'Amoxicillin 400mg + Clavulanic Acid 57mg', company: 'GlaxoSmithKline (GSK)', price: 68, dosageForm: 'Oral Suspension', category: 'Pediatric Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-augm-5', name: 'Augmentin ES 600mg Suspension 100ml', nameAr: 'أوجمنتين إي إس 600 مجم معلق 100 مل', activeIngredient: 'Amoxicillin 600mg + Clavulanic Acid 42.9mg', company: 'GlaxoSmithKline (GSK)', price: 89, dosageForm: 'Oral Suspension', category: 'Pediatric Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-hibi-1', name: 'Hibiotic 1g 14 Tablets', nameAr: 'هايبايوتك 1 جرام 14 قرص مضاد حيوي', activeIngredient: 'Amoxicillin 875mg + Clavulanic Acid 125mg', company: 'Amoun', price: 98, dosageForm: 'Tablet', category: 'Broad Spectrum Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-hibi-2', name: 'Hibiotic 625mg 10 Tablets', nameAr: 'هايبايوتك 625 مجم 10 أقراص', activeIngredient: 'Amoxicillin 500mg + Clavulanic Acid 125mg', company: 'Amoun', price: 68, dosageForm: 'Tablet', category: 'Broad Spectrum Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-hibi-3', name: 'Hibiotic 457mg Suspension 60ml', nameAr: 'هايبايوتك 457 مجم معلق للأطفال 60 مل', activeIngredient: 'Amoxicillin 400mg + Clavulanic Acid 57mg', company: 'Amoun', price: 55, dosageForm: 'Oral Suspension', category: 'Pediatric Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-cura-1', name: 'Curam 1g 14 Tablets', nameAr: 'كيورام 1 جرام 14 قرص مضاد حيوي واسع المجال', activeIngredient: 'Amoxicillin 875mg + Clavulanic Acid 125mg', company: 'Sandoz', price: 102, dosageForm: 'Tablet', category: 'Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-cura-2', name: 'Curam 625mg 12 Tablets', nameAr: 'كيورام 625 مجم 12 قرص', activeIngredient: 'Amoxicillin 500mg + Clavulanic Acid 125mg', company: 'Sandoz', price: 72, dosageForm: 'Tablet', category: 'Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-cura-3', name: 'Curam 457mg Suspension 70ml', nameAr: 'كيورام 457 مجم معلق 70 مل', activeIngredient: 'Amoxicillin 400mg + Clavulanic Acid 57mg', company: 'Sandoz', price: 59, dosageForm: 'Oral Suspension', category: 'Pediatric Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-flum-1', name: 'Flumox 500mg 16 Capsules', nameAr: 'فلوموكس 500 مجم 16 كبسولة', activeIngredient: 'Amoxicillin 250mg + Flucloxacillin 250mg', company: 'EIPICO', price: 42, dosageForm: 'Capsule', category: 'Broad Spectrum Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-flum-2', name: 'Flumox 1g 16 Tablets', nameAr: 'فلوموكس 1 جرام 16 قرص مضاد حيوي', activeIngredient: 'Amoxicillin 500mg + Flucloxacillin 500mg', company: 'EIPICO', price: 68, dosageForm: 'Tablet', category: 'Broad Spectrum Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-flum-3', name: 'Flumox 250mg Suspension 100ml', nameAr: 'فلوموكس 250 مجم معلق 100 مل للأطفال', activeIngredient: 'Amoxicillin + Flucloxacillin', company: 'EIPICO', price: 29, dosageForm: 'Oral Suspension', category: 'Pediatric Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-zith-1', name: 'Zithromax 500mg 3 Capsules', nameAr: 'زيثرومكس 500 مجم 3 كبسولات مضاد حيوي', activeIngredient: 'Azithromycin (500mg)', company: 'Pfizer', price: 58.5, dosageForm: 'Capsule', category: 'Macrolide Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-zith-2', name: 'Zithrokan 500mg 3 Capsules', nameAr: 'زيثروكان 500 مجم 3 كبسولات', activeIngredient: 'Azithromycin (500mg)', company: 'Hikma', price: 45, dosageForm: 'Capsule', category: 'Macrolide Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-zith-3', name: 'Zithromax Suspension 22.5ml', nameAr: 'زيثرومكس معلق للأطفال 22.5 مل', activeIngredient: 'Azithromycin (200mg/5ml)', company: 'Pfizer', price: 52, dosageForm: 'Oral Suspension', category: 'Pediatric Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-cipr-1', name: 'Ciprofar 500mg 10 Tablets', nameAr: 'سيبروفار 500 مجم 10 أقراص', activeIngredient: 'Ciprofloxacin 500mg', company: 'Pharco', price: 48, dosageForm: 'Tablet', category: 'Fluoroquinolone Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-cipr-2', name: 'Ciprofar 750mg 10 Tablets', nameAr: 'سيبروفار 750 مجم 10 أقراص', activeIngredient: 'Ciprofloxacin 750mg', company: 'Pharco', price: 62, dosageForm: 'Tablet', category: 'Fluoroquinolone Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-tava-1', name: 'Tavanic 500mg 5 Tablets', nameAr: 'تافانيك 500 مجم 5 أقراص مضاد حيوي للصدر والجهاز البولي', activeIngredient: 'Levofloxacin 500mg', company: 'Sanofi', price: 85, dosageForm: 'Tablet', category: 'Fluoroquinolone Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-flag-1', name: 'Flagyl 500mg 20 Tablets', nameAr: 'فلاجيل 500 مجم 20 قرص مطهر معوي', activeIngredient: 'Metronidazole (500mg)', company: 'Sanofi', price: 32, dosageForm: 'Tablet', category: 'Antiprotozoal / Antibacterial', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-flag-2', name: 'Flagyl 250mg 20 Tablets', nameAr: 'فلاجيل 250 مجم 20 قرص مطهر معوي', activeIngredient: 'Metronidazole (250mg)', company: 'Sanofi', price: 21, dosageForm: 'Tablet', category: 'Antiprotozoal / Antibacterial', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-flag-3', name: 'Flagyl Suspension 120ml', nameAr: 'فلاجيل شراب معلق 120 مل للأطفال', activeIngredient: 'Metronidazole (125mg/5ml)', company: 'Sanofi', price: 18.5, dosageForm: 'Oral Suspension', category: 'Antiprotozoal / Pediatric', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-anti-1', name: 'Antinal 220mg 24 Capsules', nameAr: 'أنتينال 220 مجم 24 كبسولة مطهر معوي وللإسهال', activeIngredient: 'Nifuroxazide 220mg', company: 'Amoun', price: 38, dosageForm: 'Capsule', category: 'Antidiarrheal / Intestinal Antiseptic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-anti-2', name: 'Antinal Suspension 60ml', nameAr: 'أنتينال شراب معلق 60 مل للأطفال', activeIngredient: 'Nifuroxazide 220mg/5ml', company: 'Amoun', price: 19.5, dosageForm: 'Oral Suspension', category: 'Antidiarrheal / Pediatric', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-stre-1', name: 'Streptoquin 20 Tablets', nameAr: 'ستربتوكين 20 قرص لعلاج الإسهال والمغص المعوي', activeIngredient: 'Diiodohydroxyquinoline + Phthalylsulfathiazole + Streptomycin', company: 'Medical Union Pharmaceuticals (MUP)', price: 21, dosageForm: 'Tablet', category: 'Antidiarrheal', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-nana-1', name: 'Nanazoxid 500mg 18 Tablets', nameAr: 'نانازوكسيد 500 مجم 18 قرص مطهر معوي وللطفيليات', activeIngredient: 'Nitazoxanide 500mg', company: 'Utopia', price: 68, dosageForm: 'Tablet', category: 'Antiparasitic / Antiprotozoal', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  // ==========================================
  // 3. GASTROINTESTINAL & DIGESTIVE SYSTEM
  // ==========================================
  { id: 'drug-visc-1', name: 'Visceralgine 50mg 20 Tablets', nameAr: 'فيسرالجين 50 مجم 20 قرص لمغص البطن والتقلصات', activeIngredient: 'Tiemonium Methylsulfate 50mg', company: 'Sedico', price: 31.5, dosageForm: 'Tablet', category: 'Antispasmodic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-visc-2', name: 'Visceralgine Syrup 120ml', nameAr: 'فيسرالجين شراب 120 مل مهدئ لتقلصات الأمعاء', activeIngredient: 'Tiemonium Methylsulfate (10mg/5ml)', company: 'Sedico', price: 18, dosageForm: 'Syrup', category: 'Antispasmodic / Pediatric', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-visc-3', name: 'Visceralgine 5mg/2ml 6 Ampoules', nameAr: 'فيسرالجين 6 أمبولات حقن عضل/وريد للتقلصات', activeIngredient: 'Tiemonium Methylsulfate (5mg/2ml)', company: 'Sedico', price: 33, dosageForm: 'Injection Ampoule', category: 'Antispasmodic', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-spas-1', name: 'Spasmo-Digestin 30 Tablets', nameAr: 'سباسمو ديجستين 30 قرص مهضم ومضاد للانتفاخ والتقلصات', activeIngredient: 'Papain + Sanzyme + Dehydrocholic Acid + Dicyclomine + Simethicone', company: 'Pharco', price: 36, dosageForm: 'Tablet', category: 'Digestive Enzyme / Antispasmodic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-cont-1', name: 'Controloc 40mg 14 Tablets', nameAr: 'كونترولوك 40 مجم 14 قرص لعلاج الحموضة وقرحة المعدة', activeIngredient: 'Pantoprazole 40mg', company: 'Takeda', price: 92, dosageForm: 'Tablet', category: 'Proton Pump Inhibitor (PPI)', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-cont-2', name: 'Controloc 20mg 14 Tablets', nameAr: 'كونترولوك 20 مجم 14 قرص', activeIngredient: 'Pantoprazole 20mg', company: 'Takeda', price: 58, dosageForm: 'Tablet', category: 'Proton Pump Inhibitor (PPI)', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-nexi-1', name: 'Nexium 40mg 14 Tablets', nameAr: 'نيكسيوم 40 مجم 14 قرص لعلاج ارتجاع المريء وحموضة المعدة', activeIngredient: 'Esomeprazole 40mg', company: 'AstraZeneca', price: 146, dosageForm: 'Tablet', category: 'Proton Pump Inhibitor (PPI)', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-nexi-2', name: 'Nexium 20mg 14 Tablets', nameAr: 'نيكسيوم 20 مجم 14 قرص', activeIngredient: 'Esomeprazole 20mg', company: 'AstraZeneca', price: 98, dosageForm: 'Tablet', category: 'Proton Pump Inhibitor (PPI)', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-moti-1', name: 'Motilium 10mg 40 Tablets', nameAr: 'موتيليوم 10 مجم 40 قرص لعلاج الغثيان والقيء والمعدة', activeIngredient: 'Domperidone 10mg', company: 'Janssen', price: 42, dosageForm: 'Tablet', category: 'Antiemetic / Prokinetic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-moti-2', name: 'Motilium Suspension 200ml', nameAr: 'موتيليوم معلق 200 مل للأطفال للقيء', activeIngredient: 'Domperidone 1mg/ml', company: 'Janssen', price: 38, dosageForm: 'Oral Suspension', category: 'Antiemetic / Pediatric', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-prim-1', name: 'Primperan 10mg 20 Tablets', nameAr: 'بريمبران 10 مجم 20 قرص للقيء والغثيان', activeIngredient: 'Metoclopramide 10mg', company: 'Sanofi', price: 18, dosageForm: 'Tablet', category: 'Antiemetic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-prim-2', name: 'Primperan 10mg/2ml 6 Ampoules', nameAr: 'بريمبران 6 أمبولات حقن للقيء عضل/وريد', activeIngredient: 'Metoclopramide (10mg/2ml)', company: 'Sanofi', price: 27, dosageForm: 'Injection Ampoule', category: 'Antiemetic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-euca-1', name: 'Eucabon 30 Charcoal Tablets', nameAr: 'إيوكابون 30 قرص فحم نباتي للانتفاخ والغازات', activeIngredient: 'Activated Charcoal + Senna', company: 'Fawzy', price: 24, dosageForm: 'Tablet', category: 'Antiflatulent', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-gavi-1', name: 'Gaviscon Peppermint Suspension 300ml', nameAr: 'جافيسكون شراب بالنعناع للحموضة وحرقان الصدر', activeIngredient: 'Sodium Alginate + Sodium Bicarbonate', company: 'Reckitt Benckiser', price: 85, dosageForm: 'Oral Liquid', category: 'Antacid', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-dusp-1', name: 'Duspatalin 135mg 30 Tablets', nameAr: 'دسباتالين 135 مجم 30 قرص لعلاج القولون العصبي', activeIngredient: 'Mebeverine HCl 135mg', company: 'Abbott', price: 68, dosageForm: 'Tablet', category: 'Colonic Antispasmodic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-dusp-2', name: 'Duspatalin Retard 200mg 30 Capsules', nameAr: 'دسباتالين ريتارد 200 مجم كبسولات ممتدة المفعول للقولون', activeIngredient: 'Mebeverine HCl 200mg', company: 'Abbott', price: 82, dosageForm: 'SR Capsule', category: 'Colonic Antispasmodic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-colo-1', name: 'Colona 30 Tablets', nameAr: 'كولونا 30 قرص لالتهاب القولون العصبي والتقلصات', activeIngredient: 'Mebeverine 135mg + Sulpiride 25mg', company: 'Marcyrl', price: 38, dosageForm: 'Tablet', category: 'Irritable Bowel Syndrome Care', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  // ==========================================
  // 4. RESPIRATORY & COLD & ALLERGY
  // ==========================================
  { id: 'drug-cong-1', name: 'Congestal 20 Tablets', nameAr: 'كونجستال 20 قرص لعلاج أعراض البرد والرشح والأنفصل', activeIngredient: 'Paracetamol 650mg + Chlorpheniramine 4mg + Pseudoephedrine 60mg', company: 'Sigma', price: 31.5, dosageForm: 'Tablet', category: 'Cold & Flu', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-cong-2', name: 'Congestal Syrup 120ml', nameAr: 'كونجستال شراب 120 مل للأطفال في حالات البرد', activeIngredient: 'Paracetamol + Chlorpheniramine + Pseudoephedrine', company: 'Sigma', price: 21, dosageForm: 'Syrup', category: 'Pediatric Cold & Flu', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-otri-1', name: 'Otrivin Adult Nasal Spray 0.1% 10ml', nameAr: 'أوتريفين بخاخ أنف للكبار 0.1% مضاد للاحتقان', activeIngredient: 'Xylometazoline HCl 0.1%', company: 'GlaxoSmithKline (GSK)', price: 25, dosageForm: 'Nasal Spray', category: 'Nasal Decongestant', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-otri-2', name: 'Otrivin Adult Drops 0.1% 10ml', nameAr: 'أوتريفين نقط أنف للكبار 0.1%', activeIngredient: 'Xylometazoline HCl 0.1%', company: 'GlaxoSmithKline (GSK)', price: 18, dosageForm: 'Nasal Drops', category: 'Nasal Decongestant', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-otri-3', name: 'Otrivin Child Drops 0.05% 10ml', nameAr: 'أوتريفين نقط أنف للأطفال 0.05%', activeIngredient: 'Xylometazoline HCl 0.05%', company: 'GlaxoSmithKline (GSK)', price: 16, dosageForm: 'Nasal Drops', category: 'Pediatric Decongestant', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-otri-4', name: 'Otrivin Baby Saline Drops 15ml', nameAr: 'أوتريفين بيبي سالين نقط أنف محول ملحي للرضع', activeIngredient: 'Sodium Chloride 0.74%', company: 'GlaxoSmithKline (GSK)', price: 19.5, dosageForm: 'Nasal Drops', category: 'Pediatric Nasal Care', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-zyrt-1', name: 'Zyrtec 10mg 20 Tablets', nameAr: 'زيرتك 10 مجم 20 قرص للحساسية والارتيكاريا والرشح', activeIngredient: 'Cetirizine Dihydrochloride 10mg', company: 'UCB', price: 54, dosageForm: 'Tablet', category: 'Antihistamine', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-zyrt-2', name: 'Zyrtec Syrup 100ml', nameAr: 'زيرتك شراب 100 مل للحساسية للأطفال', activeIngredient: 'Cetirizine Dihydrochloride (5mg/5ml)', company: 'UCB', price: 33, dosageForm: 'Syrup', category: 'Antihistamine / Pediatric', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-telf-1', name: 'Telfast 180mg 20 Tablets', nameAr: 'تلفاست 180 مجم 20 قرص للحساسية الشديدة والجلدية', activeIngredient: 'Fexofenadine HCl 180mg', company: 'Sanofi', price: 90, dosageForm: 'Tablet', category: 'Antihistamine', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-telf-2', name: 'Telfast 120mg 20 Tablets', nameAr: 'تلفاست 120 مجم 20 قرص لحساسية الأنف والرشح', activeIngredient: 'Fexofenadine HCl 120mg', company: 'Sanofi', price: 72, dosageForm: 'Tablet', category: 'Antihistamine', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-selg-1', name: 'Selgon 20 Tablets', nameAr: 'سلجون 20 قرص لعلاج الكحة والسعال الجاف', activeIngredient: 'Pipazethate HCl 20mg', company: 'EIPICO', price: 18, dosageForm: 'Tablet', category: 'Cough Suppressant', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-selg-2', name: 'Selgon Oral Drops 15ml', nameAr: 'سلجون نقط للفم للأطفال لعلاج السعال', activeIngredient: 'Pipazethate HCl 40mg/ml', company: 'EIPICO', price: 14, dosageForm: 'Oral Drops', category: 'Pediatric Cough Suppressant', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-selg-3', name: 'Selgon Suppositories 6s', nameAr: 'سلجون أقماع (لبوس للأطفال للسعال والكحة)', activeIngredient: 'Pipazethate HCl 10mg', company: 'EIPICO', price: 12, dosageForm: 'Suppositories (أقماع/لبوس)', category: 'Pediatric Cough Suppressant', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-bron-1', name: 'Bronchicum Elixir Syrup 100ml', nameAr: 'برونشيكوم إكسير شراب أعشاب طبيعي للسعال والكحة', activeIngredient: 'Thyme Extract + Primula Root Extract', company: 'Sanofi', price: 42, dosageForm: 'Syrup', category: 'Herbal Cough Syrup', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-farc-1', name: 'Farcolin Respiratory Solution 20ml', nameAr: 'فاركولين محلول استنشاق لجهاز النيبولايزر 20 مل', activeIngredient: 'Salbutamol Sulfate 0.5%', company: 'Pharco', price: 15, dosageForm: 'Inhalation Solution', category: 'Bronchodilator', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-vent-1', name: 'Ventolin Inhaler 200 Doses', nameAr: 'فنتولين بخاخ أستنشاق موسع للشعب الهوائية', activeIngredient: 'Salbutamol 100mcg/dose', company: 'GlaxoSmithKline (GSK)', price: 45, dosageForm: 'Inhaler', category: 'Bronchodilator', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-avam-1', name: 'Avamys Nasal Spray 120 Doses', nameAr: 'أفاميس بخاخ أنف لعلاج حساسية الأنف والتهاب الجيوب الأنفية', activeIngredient: 'Fluticasone Furoate 27.5mcg', company: 'GlaxoSmithKline (GSK)', price: 98, dosageForm: 'Nasal Spray', category: 'Corticosteroid Nasal Spray', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  // ==========================================
  // 5. CARDIOVASCULAR & CHRONIC & DIABETES
  // ==========================================
  { id: 'drug-conc-1', name: 'Concor 5mg 30 Tablets', nameAr: 'كونكور 5 مجم 30 قرص لعلاج ضغط الدم المرتفع', activeIngredient: 'Bisoprolol Fumarate 5mg', company: 'Merck', price: 62, dosageForm: 'Tablet', category: 'Beta-Blocker / Antihypertensive', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-conc-2', name: 'Concor 5 Plus 30 Tablets', nameAr: 'كونكور 5 بلس 30 قرص', activeIngredient: 'Bisoprolol 5mg + Hydrochlorothiazide 12.5mg', company: 'Merck', price: 68, dosageForm: 'Tablet', category: 'Antihypertensive Combination', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-conc-3', name: 'Concor 10mg 30 Tablets', nameAr: 'كونكور 10 مجم 30 قرص', activeIngredient: 'Bisoprolol Fumarate 10mg', company: 'Merck', price: 84, dosageForm: 'Tablet', category: 'Beta-Blocker', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-capo-1', name: 'Capoten 25mg 20 Tablets', nameAr: 'كابوتين 25 مجم 20 قرص للضغط المرتفع', activeIngredient: 'Captopril 25mg', company: 'SmithKline', price: 24, dosageForm: 'Tablet', category: 'ACE Inhibitor', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-capo-2', name: 'Capoten 50mg 20 Tablets', nameAr: 'كابوتين 50 مجم 20 قرص', activeIngredient: 'Captopril 50mg', company: 'SmithKline', price: 38, dosageForm: 'Tablet', category: 'ACE Inhibitor', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-gluc-1', name: 'Glucophage 1000mg 30 Tablets', nameAr: 'جلوكوفاج 1000 مجم 30 قرص لعلاج مرض السكري', activeIngredient: 'Metformin HCl 1000mg', company: 'Merck', price: 60, dosageForm: 'Tablet', category: 'Antidiabetic (Biguanide)', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-gluc-2', name: 'Glucophage 500mg 30 Tablets', nameAr: 'جلوكوفاج 500 مجم 30 قرص', activeIngredient: 'Metformin HCl 500mg', company: 'Merck', price: 31.5, dosageForm: 'Tablet', category: 'Antidiabetic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-gluc-3', name: 'Glucophage XR 1000mg 30 Tablets', nameAr: 'جلوكوفاج إكس آر 1000 مجم ممتد المفعول', activeIngredient: 'Metformin HCl 1000mg Sustained Release', company: 'Merck', price: 75, dosageForm: 'XR Tablet', category: 'Antidiabetic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-amar-1', name: 'Amaryl 2mg 30 Tablets', nameAr: 'أماريل 2 مجم 30 قرص خافض لسكر الدم', activeIngredient: 'Glimepiride 2mg', company: 'Sanofi', price: 54, dosageForm: 'Tablet', category: 'Antidiabetic (Sulfonylurea)', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-amar-2', name: 'Amaryl 3mg 30 Tablets', nameAr: 'أماريل 3 مجم 30 قرص', activeIngredient: 'Glimepiride 3mg', company: 'Sanofi', price: 63, dosageForm: 'Tablet', category: 'Antidiabetic', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-ator-1', name: 'Ator 20mg 20 Tablets', nameAr: 'أتور 20 مجم 20 قرص لخفض الكوليسترول والدهون', activeIngredient: 'Atorvastatin 20mg', company: 'EIPICO', price: 58, dosageForm: 'Tablet', category: 'Statin / Lipid-Lowering', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-ator-2', name: 'Ator 40mg 20 Tablets', nameAr: 'أتور 40 مجم 20 قرص', activeIngredient: 'Atorvastatin 40mg', company: 'EIPICO', price: 82, dosageForm: 'Tablet', category: 'Statin / Lipid-Lowering', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  // ==========================================
  // 6. VITAMINS & NEURO & DERMATOLOGY & OTIC
  // ==========================================
  { id: 'drug-neur-1', name: 'Neurobion 3 Ampoules', nameAr: 'نيوروبيون 3 أمبولات حقن للأعصاب وفيتامين ب المركب', activeIngredient: 'Vitamin B1 + B6 + B12', company: 'Merck', price: 34.5, dosageForm: 'Injection Ampoule', category: 'Vitamin B Complex', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-neur-2', name: 'Neurobion 20 Coated Tablets', nameAr: 'نيوروبيون 20 قرص مغلف للأعصاب', activeIngredient: 'Vitamin B1 + B6 + B12', company: 'Merck', price: 27, dosageForm: 'Tablet', category: 'Vitamin B Complex', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-trib-1', name: 'Tri-B 6 Ampoules', nameAr: 'تراي بي 6 أمبولات للأعصاب والفقرات', activeIngredient: 'Vitamin B1 100mg + B6 40mg + B12 1000mcg', company: 'EIPICO', price: 36, dosageForm: 'Injection Ampoule', category: 'Vitamin B Complex', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-depo-1', name: 'Depovit B12 1000mcg 5 Ampoules', nameAr: 'ديبوفيت بي 12 أمبولات 1000 ميكروجرام طويلة المفعول', activeIngredient: 'Hydroxocobalamin 1000mcg', company: 'Amoun', price: 43.5, dosageForm: 'Injection Ampoule', category: 'Vitamin B12 Supplement', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-sans-1', name: 'Sansovit with Iron Syrup 120ml', nameAr: 'سانسوفيت بالحديد شراب 120 مل فتح شهية وتقوية المناعة للأطفال', activeIngredient: 'Multivitamins + Iron', company: 'Novartis', price: 39, dosageForm: 'Syrup', category: 'Pediatric Vitamins & Iron', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-fuci-1', name: 'Fucidin 2% Cream 15g', nameAr: 'فيوسيدين 2% كريم مضاد حيوي جلدي', activeIngredient: 'Fusidic Acid 2%', company: 'LEO Pharma', price: 32.5, dosageForm: 'Topical Cream', category: 'Topical Antibiotic', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-fuci-2', name: 'Fucicort Cream 15g', nameAr: 'فيوسيكورت كريم مضاد حيوي ومضاد للالتهاب والتسلخات', activeIngredient: 'Fusidic Acid + Betamethasone', company: 'LEO Pharma', price: 43, dosageForm: 'Topical Cream', category: 'Topical Antibiotic + Corticosteroid', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-kena-1', name: 'Kenacomb Cream 15g', nameAr: 'كيناكومب كريم 15 جرام لعلاج التسلخات والالتهابات الجلدية', activeIngredient: 'Neomycin + Nystatin + Triamcinolone + Gramicidin', company: 'SmithKline', price: 36, dosageForm: 'Topical Cream', category: 'Topical Antifungal & Anti-inflammatory', isControlled: false, sourceOrigin: 'Egyptian Bank' },

  { id: 'drug-uriv-1', name: 'Urivin Effervescent 10 Sachets', nameAr: 'أوريفين فوار 10 أكياس لعلاج النقرس وأملاح اليورات', activeIngredient: 'Piperazine + Colchicine + Atropine', company: 'Nile Pharma', price: 18, dosageForm: 'Effervescent Sachet', category: 'Uric Acid Excretory', isControlled: false, sourceOrigin: 'Egyptian Bank' },
  { id: 'drug-otal-1', name: 'Otal Ear Drops 10ml', nameAr: 'أوتال نقط للأذن مسكنة ومضادة لالتهاب الأذن', activeIngredient: 'Framycetin + Gramicidin + Dexamethasone + Cinchocaine', company: 'Amoun', price: 19.5, dosageForm: 'Ear Drops', category: 'Otic Preparation', isControlled: false, sourceOrigin: 'Egyptian Bank' }
];

// Write catalog to comprehensive-drugs.json
const targetPath = path.join(__dirname, '../src/data/comprehensive-drugs.json');
fs.writeFileSync(targetPath, JSON.stringify(catalog, null, 2), 'utf-8');

console.log('Successfully updated catalog with', catalog.length, 'real clean drugs to', targetPath);
